### ISSUE TITLE
Story image URL using unparsed full "srcset" value

### ISSUE THREAD

**Issue by coordinatesystem** [samuelclay/NewsBlur#1054]
Hello,

In the story list (or grid) on the web, and in the Android app story list, the story image sometimes is using a bad URL. I can reproduce it here in a few web browsers (Chrome and Firefox on Windows) while not logged in/incognito: https://www.newsblur.com/site/452556/jwz
(Switch to grid view, collapse the story, and look for the bright red debug images.) It happens on the post titled "Yelle" from Oct 29 for example. This is what jwz said about it:

> Here's what's going on: it is seeing an IMG tag that has both SRC and SRCSET attributes, and it is trying to load SRCSET as a single URL, which is crazy-kookoopants and not at all how that works, OMG.
> 
> Which means it tried to load the URL:
> https://www.jwz.org/images/scaled/768/2017/img_7565.jpg%203300w,%20https://www.jwz.org/images/scaled/1280/2017/img_7565.jpg%201280w,%20https://www.jwz.org/images/scaled/768/2017/img_7565.jpg%20768w,%20https://www.jwz.org/images/scaled/640/2017/img_7565.jpg%20640w,%20https://www.jwz.org/images/scaled/360/2017/img_7565.jpg%20360w
> 
> Having seen this HTML in the RSS feed: https://www.jwz.org/blog/feed/
> 
```html
<IMG SRC="https://www.jwz.org/images/scaled/768/2017/img_7565.jpg" data-size="3300x2475" STYLE="width: 100%; height:auto; max-width:3300px; max-height:2475px; border: 1px solid; box-sizing: border-box; margin: 0;" SRCSET="https://www.jwz.org/images/scaled/768/2017/img_7565.jpg 3300w, https://www.jwz.org/images/scaled/1280/2017/img_7565.jpg 1280w, https://www.jwz.org/images/scaled/768/2017/img_7565.jpg 768w, https://www.jwz.org/images/scaled/640/2017/img_7565.jpg 640w, https://www.jwz.org/images/scaled/360/2017/img_7565.jpg 360w" SIZES="(max-width: 660px) 50vw, 36em">
```

Some actions, like expanding a story, seem to make it load the proper image (even in the thumbnail spot.)

**Comment by samuelclay** [comment]
Ok, I just committed b7574a1ff which should fix this issue. Let me know!

**Comment by coordinatesystem** [comment]
Looks like it's still happening for new stories, at least in the web interface.
