### ISSUE TITLE
docker installation updated, db_mongo & db_postgres container errors/restarting

### ISSUE THREAD

**Issue by luxiouronimo** [samuelclay/NewsBlur#1687]
i attempted to update my NewsBlur docker installation on a late 2012 intel mac mini running macos 10.15.7..

the db_mongo and db_postgres containers are constantly restarting, with the following errors repeating:

### db_postgres

> chmod: changing permissions of '/var/run/postgresql': Operation not permitted
> 
> 2022-05-17 00:45:13.830 UTC [1] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
> 
> 2022-05-17 00:45:13.830 UTC [1] HINT:  The server must be started by the user that owns the data directory.
> 

_if this is referring to /var/run/postgresql on the host system, that does not exist.._

### db_mongo:

> 2022-05-17T01:01:47.352+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
> 
> 2022-05-17T01:01:47.357+0000 W  ASIO     [main] No TransportLayer configured during NetworkInterface startup
> 
> 2022-05-17T01:01:47.357+0000 I  CONTROL  [initandlisten] MongoDB starting : pid=1 port=29019 dbpath=/data/db 64-bit host=9869e1187abb
> 
> 2022-05-17T01:01:47.357+0000 I  CONTROL  [initandlisten] db version v4.2.20
> 
> 2022-05-17T01:01:47.357+0000 I  CONTROL  [initandlisten] git version: 15c0712952c356cb711c13a42cb3bca8617d4ebc
> 
> 2022-05-17T01:01:47.357+0000 I  CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
> 
> 2022-05-17T01:01:47.357+0000 I  CONTROL  [initandlisten] allocator: tcmalloc
> 
> 2022-05-17T01:01:47.357+0000 I  CONTROL  [initandlisten] modules: none
> 
> 2022-05-17T01:01:47.357+0000 I  CONTROL  [initandlisten] build environment:
> 
> 2022-05-17T01:01:47.357+0000 I  CONTROL  [initandlisten]     distmod: ubuntu1804
> 
> 2022-05-17T01:01:47.357+0000 I  CONTROL  [initandlisten]     distarch: x86_64
> 
> 2022-05-17T01:01:47.357+0000 I  CONTROL  [initandlisten]     target_arch: x86_64
> 
> 2022-05-17T01:01:47.357+0000 I  CONTROL  [initandlisten] options: { net: { bindIp: "*", port: 29019 } }
> 
> 2022-05-17T01:01:47.361+0000 I  STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
> 
> 2022-05-17T01:01:47.364+0000 I  STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=3468M,cache_overflow=(file_max=0M),session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress],
> 
> 2022-05-17T01:01:47.991+0000 I  STORAGE  [initandlisten] WiredTiger message [1652749307:991952][1:0x7fefa18afb00], txn-recover: Recovering log 156 through 157
> 
> 2022-05-17T01:01:48.933+0000 I  STORAGE  [initandlisten] WiredTiger message [1652749308:933272][1:0x7fefa18afb00], txn-recover: Recovering log 157 through 157
> 
> 2022-05-17T01:01:49.802+0000 I  STORAGE  [initandlisten] WiredTiger message [1652749309:802226][1:0x7fefa18afb00], txn-recover: Main recovery loop: starting at 156/896 to 157/256
> 
> 2022-05-17T01:01:49.900+0000 I  STORAGE  [initandlisten] WiredTiger message [1652749309:900981][1:0x7fefa18afb00], txn-recover: Recovering log 156 through 157
> 
> 2022-05-17T01:01:49.978+0000 I  STORAGE  [initandlisten] WiredTiger message [1652749309:978392][1:0x7fefa18afb00], txn-recover: Recovering log 157 through 157
> 
> 2022-05-17T01:01:50.024+0000 I  STORAGE  [initandlisten] WiredTiger message [1652749310:24518][1:0x7fefa18afb00], txn-recover: Set global recovery timestamp: (0, 0)
> 
> 2022-05-17T01:01:50.050+0000 I  RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
> 
> 2022-05-17T01:01:50.057+0000 I  STORAGE  [initandlisten] No table logging settings modifications are required for existing WiredTiger tables. Logging enabled? 1
> 
> 2022-05-17T01:01:50.062+0000 I  STORAGE  [initandlisten] Timestamp monitor starting
> 
> 2022-05-17T01:01:50.064+0000 I  CONTROL  [initandlisten] 
> 
> 2022-05-17T01:01:50.064+0000 I  CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
> 
> 2022-05-17T01:01:50.064+0000 I  CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
> 
> 2022-05-17T01:01:50.064+0000 I  CONTROL  [initandlisten] 
> 
> 2022-05-17T01:01:50.084+0000 F  CONTROL  [initandlisten] ** IMPORTANT: UPGRADE PROBLEM: Found an invalid featureCompatibilityVersion document (ERROR: BadValue: Invalid value for version, found 3.6, expected '4.2' or '4.0'. Contents of featureCompatibilityVersion document in admin.system.version: { _id: "featureCompatibilityVersion", version: "3.6" }. See https://docs.mongodb.com/manual/release-notes/4.2-compatibility/#feature-compatibility.). If the current featureCompatibilityVersion is below 4.0, see the documentation on upgrading at https://docs.mongodb.com/manual/release-notes/4.2/#upgrade-procedures.
> 
> 2022-05-17T01:01:50.084+0000 I  REPL     [initandlisten] Stepping down the ReplicationCoordinator for shutdown, waitTime: 10000ms
> 
> 2022-05-17T01:01:50.084+0000 I  SHARDING [initandlisten] Shutting down the WaitForMajorityService
> 
> 2022-05-17T01:01:50.084+0000 I  NETWORK  [initandlisten] shutdown: going to close listening sockets...
> 
> 2022-05-17T01:01:50.084+0000 I  NETWORK  [initandlisten] Shutting down the global connection pool
> 
> 2022-05-17T01:01:50.084+0000 I  STORAGE  [initandlisten] Shutting down the FlowControlTicketholder
> 
> 2022-05-17T01:01:50.084+0000 I  -        [initandlisten] Stopping further Flow Control ticket acquisitions.
> 
> 2022-05-17T01:01:50.084+0000 I  STORAGE  [initandlisten] Shutting down the PeriodicThreadToAbortExpiredTransactions
> 
> 2022-05-17T01:01:50.085+0000 I  STORAGE  [initandlisten] Shutting down the PeriodicThreadToDecreaseSnapshotHistoryIfNotNeeded
> 
> 2022-05-17T01:01:50.085+0000 I  REPL     [initandlisten] Shutting down the ReplicationCoordinator
> 
> 2022-05-17T01:01:50.085+0000 I  SHARDING [initandlisten] Shutting down the ShardingInitializationMongoD
> 
> 2022-05-17T01:01:50.085+0000 I  REPL     [initandlisten] Enqueuing the ReplicationStateTransitionLock for shutdown
> 
> 2022-05-17T01:01:50.085+0000 I  -        [initandlisten] Killing all operations for shutdown
> 
> 2022-05-17T01:01:50.085+0000 I  COMMAND  [initandlisten] Shutting down all open transactions
> 
> 2022-05-17T01:01:50.085+0000 I  REPL     [initandlisten] Acquiring the ReplicationStateTransitionLock for shutdown
> 
> 2022-05-17T01:01:50.085+0000 I  INDEX    [initandlisten] Shutting down the IndexBuildsCoordinator
> 
> 2022-05-17T01:01:50.085+0000 I  NETWORK  [initandlisten] Shutting down the ReplicaSetMonitor
> 
> 2022-05-17T01:01:50.085+0000 I  CONTROL  [initandlisten] Shutting down free monitoring
> 
> 2022-05-17T01:01:50.085+0000 I  FTDC     [initandlisten] Shutting down full-time data capture
> 
> 2022-05-17T01:01:50.085+0000 I  STORAGE  [initandlisten] Shutting down the HealthLog
> 
> 2022-05-17T01:01:50.085+0000 I  STORAGE  [initandlisten] Shutting down the storage engine
> 
> 2022-05-17T01:01:50.085+0000 I  STORAGE  [initandlisten] Deregistering all the collections
> 
> 2022-05-17T01:01:50.085+0000 I  STORAGE  [initandlisten] Timestamp monitor shutting down
> 
> 2022-05-17T01:01:50.085+0000 I  STORAGE  [initandlisten] WiredTigerKVEngine shutting down
> 
> 2022-05-17T01:01:50.085+0000 I  STORAGE  [initandlisten] Shutting down session sweeper thread
> 
> 2022-05-17T01:01:50.085+0000 I  STORAGE  [initandlisten] Finished shutting down session sweeper thread
> 
> 2022-05-17T01:01:50.085+0000 I  STORAGE  [initandlisten] Shutting down journal flusher thread
> 
> 2022-05-17T01:01:50.153+0000 I  STORAGE  [initandlisten] Finished shutting down journal flusher thread
> 
> 2022-05-17T01:01:50.153+0000 I  STORAGE  [initandlisten] Shutting down checkpoint thread
> 
> 2022-05-17T01:01:50.153+0000 I  STORAGE  [initandlisten] Finished shutting down checkpoint thread
> 
> 2022-05-17T01:01:50.153+0000 I  STORAGE  [initandlisten] Downgrading WiredTiger datafiles.
> 
> 2022-05-17T01:01:50.236+0000 I  STORAGE  [initandlisten] WiredTiger message [1652749310:236519][1:0x7fefa18afb00], txn-recover: Recovering log 157 through 158
> 
> 2022-05-17T01:01:51.073+0000 I  STORAGE  [initandlisten] WiredTiger message [1652749311:73801][1:0x7fefa18afb00], txn-recover: Recovering log 158 through 158
> 
> 2022-05-17T01:01:52.052+0000 I  STORAGE  [initandlisten] WiredTiger message [1652749312:52378][1:0x7fefa18afb00], txn-recover: Main recovery loop: starting at 157/2176 to 158/256
> 
> 2022-05-17T01:01:52.150+0000 I  STORAGE  [initandlisten] WiredTiger message [1652749312:150536][1:0x7fefa18afb00], txn-recover: Recovering log 157 through 158
> 
> 2022-05-17T01:01:52.228+0000 I  STORAGE  [initandlisten] WiredTiger message [1652749312:228490][1:0x7fefa18afb00], txn-recover: Recovering log 158 through 158
> 
> 2022-05-17T01:01:52.273+0000 I  STORAGE  [initandlisten] WiredTiger message [1652749312:273956][1:0x7fefa18afb00], txn-recover: Set global recovery timestamp: (0, 0)
> 
> 2022-05-17T01:01:52.383+0000 I  STORAGE  [initandlisten] shutdown: removing fs lock...
> 
> 2022-05-17T01:01:52.384+0000 I  -        [initandlisten] Dropping the scope cache for shutdown
> 
> 2022-05-17T01:01:52.384+0000 I  CONTROL  [initandlisten] now exiting
> 
> 2022-05-17T01:01:52.384+0000 I  CONTROL  [initandlisten] shutting down with code:62
> 

_no idea where to start with this.._

**Comment by samuelclay** [comment]
Thanks for posting this. I fixed the mongo issue in 2d4b1f508. Pull latest and do a `make nb` and it should perform a migration that fixes it (as well as downgrades to a mongo 4.0 server that will boot with a 3.6 feature compatibility version).

We should figure out how to upgrade multiple levels of mongodb, since some users won't pull latest for months at a time. So when they finally do, their mongo won't start because of this bug. I hate to send them to specific commits and run migrations. Maybe just mentioning changing docker-compose.yml to use a compatibility version, and then run migrations until it catches up.

As for the postgres bug, that's because I made a change 4 weeks ago for how the postgres container is created, giving it your user. The answer is to perform a `chown user.user -R docker/volumes/postgres` but that may not work. Let me know how that does.

**Comment by luxiouronimo** [comment]
ok some progress; the db_mongo container seems to be running stably, the db_postgres is still having issues tho…

### db_postgres

> mm26:NewsBlur dlux$ chown -R dlux:staff docker/volumes/postgres/

this worked, but still errors:

> chmod: changing permissions of '/var/run/postgresql': Operation not permitted
> 
> 2022-05-17 19:37:46.325 UTC [1] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
> 
> 2022-05-17 19:37:46.325 UTC [1] HINT:  The server must be started by the user that owns the data directory.
> 
> chmod: changing permissions of '/var/run/postgresql': Operation not permitted
> 
> 2022-05-17 19:37:47.606 UTC [1] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
> 
> 2022-05-17 19:37:47.606 UTC [1] HINT:  The server must be started by the user that owns the data directory.
> 
> chmod: changing permissions of '/var/run/postgresql': Operation not permitted
> 
> 2022-05-17 19:37:49.185 UTC [1] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
> 
> 2022-05-17 19:37:49.185 UTC [1] HINT:  The server must be started by the user that owns the data directory.
> 
> chmod: changing permissions of '/var/run/postgresql': Operation not permitted
> 
> 2022-05-17 19:37:51.349 UTC [1] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
> 
> 2022-05-17 19:37:51.349 UTC [1] HINT:  The server must be started by the user that owns the data directory.
> 
> chmod: changing permissions of '/var/run/postgresql': Operation not permitted
> 
> 2022-05-17 19:37:53.279 UTC [1] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
> 
> 
> PostgreSQL Database directory appears to contain a database; Skipping initialization
> 
> 
> 
> PostgreSQL Database directory appears to contain a database; Skipping initialization
> 
> 
> 
> PostgreSQL Database directory appears to contain a database; Skipping initialization
> 
> 
> 
> PostgreSQL Database directory appears to contain a database; Skipping initialization
> 
> 
> 
> PostgreSQL Database directory appears to contain a database; Skipping initialization
> 
> 
> 
> PostgreSQL Database directory appears to contain a database; Skipping initialization
> 
> 
> 
> PostgreSQL Database directory appears to contain a database; Skipping initialization
> 
> 
> 
> PostgreSQL Database directory appears to contain a database; Skipping initialization
> 
> 
> 
> PostgreSQL Database directory appears to contain a database; Skipping initialization
> 
> 
> 
> PostgreSQL Database directory appears to contain a database; Skipping initialization
> 
> 
> 2022-05-17 19:37:53.279 UTC [1] HINT:  The server must be started by the user that owns the data directory.
> 
> chmod: changing permissions of '/var/run/postgresql': Operation not permitted
> 
> 2022-05-17 19:37:55.774 UTC [1] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
> 
> 2022-05-17 19:37:55.774 UTC [1] HINT:  The server must be started by the user that owns the data directory.
> 
> chmod: changing permissions of '/var/run/postgresql': Operation not permitted
> 
> 2022-05-17 19:37:59.705 UTC [1] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
> 
> 2022-05-17 19:37:59.705 UTC [1] HINT:  The server must be started by the user that owns the data directory.
> 
> chmod: changing permissions of '/var/run/postgresql': Operation not permitted
> 
> 2022-05-17 19:38:06.665 UTC [1] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
> 
> 2022-05-17 19:38:06.665 UTC [1] HINT:  The server must be started by the user that owns the data directory.
> 
> chmod: changing permissions of '/var/run/postgresql': Operation not permitted
> 
> 2022-05-17 19:38:20.115 UTC [1] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
> 
> 2022-05-17 19:38:20.115 UTC [1] HINT:  The server must be started by the user that owns the data directory.
> 
> chmod: changing permissions of '/var/run/postgresql': Operation not permitted
> 
> 2022-05-17 19:38:46.206 UTC [1] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
> 
> 2022-05-17 19:38:46.206 UTC [1] HINT:  The server must be started by the user that owns the data directory.
>

**Comment by samuelclay** [comment]
Ok, I reverted fd298e7980b07503ec0bae3e9e207a8b8685e6b8. Try pulling latest and run a `make nb`.

**Comment by luxiouronimo** [comment]
hot dog! it's running now! =D

anything i should watch out for in the future? maybe just updating more often..?

**Comment by samuelclay** [comment]
You should always be able to update, I just didn't know those would break. But I want you to expect it to run clean, so I'm quickly fixing these types of issues now.

**Comment by luxiouronimo** [comment]
also fyi, if it's useful, there was this warining/output while running make nb, tho things do appear to be running:

> docker exec newsblur_web ./manage.py migrate
>  ---> Starting NewsBlur development server...
> Operations to perform:
>   Apply all migrations: admin, analyzer, auth, contenttypes, feed_import, ipn, oauth2_provider, profile, push, reader, recommendations, rss_feeds, sessions, sites, social, zebra
> Running migrations:
>   Applying rss_feeds.0003_mongo_version_4_0...
>  ---> Current MongoDB featureCompatibilityVersion: 3.6
> Traceback (most recent call last):
>   File "/srv/newsblur/./manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
>     utility.execute()
>   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
>     output = self.handle(*args, **options)
>   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 85, in wrapped
>     res = handle_func(*args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 243, in handle
>     post_migrate_state = executor.migrate(
>   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 117, in migrate
>     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
>   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
>     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
>   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
>     state = migration.apply(state, schema_editor)
>   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/migration.py", line 124, in apply
>     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
>   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
>     self.code(from_state.apps, schema_editor)
>   File "/srv/newsblur/apps/rss_feeds/migrations/0003_mongo_version_4_0.py", line 15, in set_mongo_feature_compatibility_version
>     new_version = doc["featureCompatibilityVersion"]["version"]
> KeyError: 'featureCompatibilityVersion'
> make: [nb] Error 1 (ignored)
> docker exec newsblur_web ./manage.py loaddata config/fixtures/bootstrap.json
>  ---> Starting NewsBlur development server...
> Installed 8 object(s) from 1 fixture(s)

**Comment by samuelclay** [comment]
Thanks for letting me know, fixed in 5d3ec41c5

**Comment by luxiouronimo** [comment]
i found this re: exit code 137

> ### How do I fix exit code 137?
> As it turns out this code is commonly associated with Docker for Mac not having enough RAM allocated to it. More specifically the Linux OOM (out of memory) Killer, kicked in and terminated the process. So it is an easy fix, go to the Docker Menu and select Preferences then the Advanced tab and increase the Memory.

my docker is currently configured with 8 GB of memory (preferences > resources > advanced); i did a `make nb` to make sure the error was present before increasing the memory, but the error was not present..

i'll keep an eye out for this error in the future and if/when i experience it again, see if i can remedy it by allocating more memory..
