### ISSUE TITLE
iOS: Marking a feed as read takes you to the wrong feed

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1747]
I believe there are two issues we should fix: 

* The next feed algorithm doesn't take into account muted feeds and should skip them
* The next feed algorithm also opens the next feed even if it doesn't have unreads

**Comment by samuelclay** [comment]
This isn't working well with muted feeds.

**Comment by samuelclay** [comment]
This is very oddly broken now and leads to loading dozens of feeds in successive order. It's also breaking for users right now: https://forum.newsblur.com/t/crash-on-mark-all-read/9718/2

Are you able to repro any crashes or wonky behavior? I'm reading in Unread view in a folder with lots of muted feeds.

**Comment by Dejal** [comment]
The way it works is it selects the next feed (or folder); if that doesn't have any unread, it goes on to the next one, and so on. So it has a visual scanning to find the next unread feed. I may be able to modify it to just jump to the next unread feed, if you don't like the visual indicator.

I can't reproduce any crash, though, with or without that preference, and on iPhone or iPad. Any more clues?

Otherwise, in a day or two Apple will provide crash logs that might help.

(I'll keep an eye on it, and give priority attention to critical issues.)

**Comment by samuelclay** [comment]
Here's a video of it happening for another user: https://forum.newsblur.com/t/crash-on-mark-all-read/9718/3

**Comment by samuelclay** [comment]
I would login to my account and read stories in the Any Broken Feeds folder.

**Comment by Dejal** [comment]
Hmm. There was an issue where it isn't going into the next unread folder, which I've just fixed, but is isn't crashing for me.

I tried your username on my iPhone and the Simulator, and didn't get a crash.

Try again with this change, and share a screen recording if it still misbehaves. And if it does crash, perhaps run in Xcode to capture that.

(If it works now, you can close this issue.)

**Comment by samuelclay** [comment]
Same crash still, I'm reading a feed in the Any Broken Feeds folders and it crashes after spinning for 5 seconds on the feed list.

**Comment by samuelclay** [comment]
Here's a video

https://user-images.githubusercontent.com/44229/202875487-644c9b5c-11cf-4dbd-9a4b-5b13fbfe21e4.MOV

**Comment by Dejal** [comment]
The video was helpful, thanks; the key was that you were using Unread intelligence mode.

**Comment by samuelclay** [comment]
This fixes the crash but there's still an issue. When the next folder is collapsed, this takes you to the wrong feed. See video. 

https://user-images.githubusercontent.com/44229/203101501-00c2ba53-d466-45f0-b01a-52a7938857b9.MOV
