### ISSUE TITLE
iOS: Date of 12:00a story says "yesterday", but should be "today"

### ISSUE THREAD

**Issue by axlekb** [samuelclay/NewsBlur#491]
Date of 12:00a story says "yesterday", even though it should be today.

![image](https://f.cloud.github.com/assets/2972314/2242852/d3802d94-9d12-11e3-93e7-01fa97e52472.png)

**Comment by samuelclay** [comment]
I believe this was fixed.

**Comment by axlekb** [comment]
It is actually not fixed. Today's xkcd has the same problem (at least on iOS app)
